### ISSUE TITLE
`pesterchum` launcher doesn't work (Linux)

### ISSUE THREAD

**Issue by passcod** [kiooeht/pesterchum#11]
Which is because you've hardcoded `python2.6` in, thus:

```
#!/bin/sh

cd `dirname $0`
python2.6 pesterchum.py $@
```

But now, the current stable python version is 2.7.3. Hence this fails on any machine which has got a modern, updated python 2. The fix is pretty simple, just `python2` instead. I have no idea whether every python install has got `python2` or not, but it seems likely.

**Comment by kiooeht** [comment]
Pulled your changes to the launcher and the README markdown.
